on: push
name: 🚀 Deploy minicart.ch
jobs:
  web-deploy:
    name: 🎉 Deploy minicart.ch
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_APP_URL }}
        username: ${{ secrets.FTP_APP_USER }}
        password: ${{ secrets.FTP_APP_PASS }}
